### ISSUE TITLE
[BUG] fast ranges not working out of the box

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/whereabouts#518]
**Describe the bug**
Using fast ranges results

**Expected behavior**
The pod should come up, however, it fails with:

```
  Warning  FailedCreatePodSandBox  7s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_samplepod_default_514048e8-7b94-4cf7-8711-17adb72f0ac7_0(c88719557a2b8b049c0013ae7c62a98a37841d5961b6ab87e87b2b7c2b578969): error adding pod default_samplepod to CNI network "multus-cni-network": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: 'ContainerID:"c88719557a2b8b049c0013ae7c62a98a37841d5961b6ab87e87b2b7c2b578969" Netns:"/var/run/netns/e21fd2c7-625b-41fd-80ec-1d23c18c2ef3" IfName:"eth0" Args:"IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=samplepod;K8S_POD_INFRA_CONTAINER_ID=c88719557a2b8b049c0013ae7c62a98a37841d5961b6ab87e87b2b7c2b578969;K8S_POD_UID=514048e8-7b94-4cf7-8711-17adb72f0ac7" Path:"" ERRORED: error configuring pod [default/samplepod] networking: [default/samplepod/514048e8-7b94-4cf7-8711-17adb72f0ac7:whereaboutsexample]: error adding container to network "whereaboutsexample": netplugin failed: "2024-11-27T05:09:21+09:00 [debug] Used defaults from parsed flat file config @ /etc/cni/net.d/whereabouts.d/whereabouts.conf\n2024-11-27T05:09:21+09:00 [debug] ADD - IPAM configuration successfully read: {Name:whereaboutsexample Type:whereabouts Routes:[] Addresses:[] IPRanges:[{OmitRanges:[] Range:192.168.2.0/24 RangeStart:192.168.2.0 RangeEnd:<nil>}] OmitRanges:[] DNS:{Nameservers:[] Domain: Search:[] Options:[]} Range: NodeSliceSize:/22 RangeStart:<nil> RangeEnd:<nil> GatewayStr: LeaderLeaseDuration:1500 LeaderRenewDeadline:1000 LeaderRetryPeriod:500 LogFile:/var/log/whereabouts.log LogLevel:debug ReconcilerCronExpression:30 4 * * * OverlappingRanges:true SleepForRace:0 Gateway:<nil> Kubernetes:{KubeConfigPath:/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig K8sAPIRoot:} ConfigurationPath: PodName:samplepod PodNamespace:default NetworkName:donkeykongjr}\n2024-11-27T05:09:21+09:00 [debug] Beginning IPAM for ContainerID: \"c88719557a2b8b049c0013ae7c62a98a37841d5961b6ab87e87b2b7c2b578969\" - podRef: \"default/samplepod\" - ifName: \"net1\"\n2024-11-27T05:09:21+09:00 [debug] discovered current hostname as: labkubedualhost-node-1\n2024-11-27T05:09:21+09:00 [debug] ipam namespace is kube-system\n2024-11-27T05:09:21+09:00 [error] error getting node slice kube-system/donkeykongjr nodeslicepools.whereabouts.cni.cncf.io \"donkeykongjr\" not found\n2024-11-27T05:09:21+09:00 [error] Failed to create leader elector: nodeslicepools.whereabouts.cni.cncf.io \"donkeykongjr\" not found\n2024-11-27T05:09:21+09:00 [debug] Started leader election\nE1127 05:09:21.599030  105556 runtime.go:79] Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 41 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1636d20, 0x2642050})\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00050a380?})\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b\npanic({0x1636d20?, 0x2642050?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x0, {0x1a88a68, 0xc0004fe2d0})\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:206 +0x43\ngithub.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes.IPManagement.func2.1()\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes/ipam.go:496 +0x68\ncreated by github.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes.IPManagement.func2 in goroutine 40\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes/ipam.go:494 +0x109\npanic: runtime error: invalid memory address or nil pointer dereference [recovered]\n\tpanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1495103]\n\ngoroutine 41 [running]:\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00050a380?})\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd\npanic({0x1636d20?, 0x2642050?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x0, {0x1a88a68, 0xc0004fe2d0})\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:206 +0x43\ngithub.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes.IPManagement.func2.1()\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes/ipam.go:496 +0x68\ncreated by github.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes.IPManagement.func2 in goroutine 40\n\t/go/src/github.com/k8snetworkplumbingwg/whereabouts/pkg/storage/kubernetes/ipam.go:494 +0x109\n"
```

This looks like a leader election issue at a glance.

**To Reproduce**

Install whereabouts with:
```
kubectl apply     -f doc/crds/daemonset-install.yaml     -f doc/crds/whereabouts.cni.cncf.io_ippools.yaml     -f doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml     -f doc/crds/whereabouts.cni.cncf.io_nodeslicepools.yaml     -f doc/crds/node-slice-controller.yaml
```

Apply this net-attach-def
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereabouts-fast-ipam
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "whereaboutsexample",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.2.0/24",
      "node_slice_size": "/22",
      "network_name": "donkeykongjr",
      "leader_lease_duration": 1500,
      "leader_renew_deadline": 1000,
      "leader_retry_period": 500,
      "log_file": "/var/log/whereabouts.log",
      "log_level": "debug"
    }
  }'
```

Create this pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: whereabouts-fast-ipam
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
```

**Environment**:
- Whereabouts version : Latest
- Kubernetes version (use `kubectl version`):  v1.30.7
- Network-attachment-definition: (above)
- Whereabouts configuration (on the host): default
- OS (e.g. from /etc/os-release): fedora
- Kernel (e.g. `uname -a`): `6.8.5-301.fc40.x86_64`

**Comment by lubronzhan** [comment]
Run into the same issue. Do I need to create a nodeslicepools object?

**Comment by lubronzhan** [comment]
```
E0516 20:23:11.760723       1 controller.go:409] "failed to create nodeslicepool" err="NodeSlicePool.whereabouts.cni.cncf.io \"\" is invalid: metadata.name: Required value: name or generateName is required" resourceName="default/macvlan-config-with-fast-ipam"
```
Ok looks like network_name is required for fast node ipam

**Comment by lubronzhan** [comment]
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"12dd2428-5632-4115-940f-f72797836a74","stage":"ResponseComplete","requestURI":"/apis/whereabouts.cni.cncf.io/v1alpha1/namespaces/kube-system/nodeslicepools","verb":"create","user":{"username":"system:serviceaccount:kube-system:whereabouts","uid":"2c1cf829-758e-4dc6-a0da-8153edc6b2a5","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["whereabouts-controller-79c45c85b6-qf8xg"],"authentication.kubernetes.io/pod-uid":["e81dd709-9b89-4d2d-8bc9-271375d45e7a"]}},"sourceIPs":["10.161.91.68"],"userAgent":"node-slice-controller/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"nodeslicepools","namespace":"kube-system","name":"macvlan-config-with-fast-ipam","apiGroup":"whereabouts.cni.cncf.io","apiVersion":"v1alpha1"},"responseStatus":{"metadata":{},"code":201},"requestReceivedTimestamp":"2025-05-16T22:17:04.294102Z","stageTimestamp":"2025-05-16T22:17:04.319298Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"whereabouts\" of ClusterRole \"whereabouts-cni\" to ServiceAccount \"whereabouts/kube-system\""}}

{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"60961b37-227b-42c2-b0a4-54f204452efe","stage":"ResponseComplete","requestURI":"/apis/whereabouts.cni.cncf.io/v1alpha1/namespaces/kube-system/nodeslicepools/macvlan-config-with-fast-ipam","verb":"delete","user":{"username":"system:serviceaccount:kube-system:generic-garbage-collector","uid":"9986418b-b1a3-461b-b86e-08df354da978","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]},"sourceIPs":["10.161.89.174"],"userAgent":"kube-controller-manager/v1.29.13+vmware.3 (linux/amd64) kubernetes/9a58e93/system:serviceaccount:kube-system:generic-garbage-collector","objectRef":{"resource":"nodeslicepools","namespace":"kube-system","name":"macvlan-config-with-fast-ipam","apiGroup":"whereabouts.cni.cncf.io","apiVersion":"v1alpha1"},"responseStatus":{"metadata":{},"status":"Success","details":{"name":"macvlan-config-with-fast-ipam","group":"whereabouts.cni.cncf.io","kind":"nodeslicepools","uid":"ea5834c8-fa92-4103-b053-fb51252cced3"},"code":200},"requestReceivedTimestamp":"2025-05-16T22:17:04.326180Z","stageTimestamp":"2025-05-16T22:17:04.342004Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:controller:generic-garbage-collector\" of ClusterRole \"system:controller:generic-garbage-collector\" to ServiceAccount \"generic-garbage-collector/kube-system\""}}
```
I noticed in audit log, there is an immediate 'delete' event conducted by garbage collector `system:controller:generic-garbage-collector`

**Comment by lubronzhan** [comment]
Ok looking at the code 
```
ObjectMeta: metav1.ObjectMeta{
				Name:      getSliceName(ipamConf),
				Namespace: c.whereaboutsNamespace,
				OwnerReferences: []metav1.OwnerReference{
					*metav1.NewControllerRef(nad, cncfV1.SchemeGroupVersion.WithKind("NetworkAttachmentDefinition")),
				},
			},
```
It's expecting the NAD in the namespace where the whereabouts pod is located. So the ownerRef points to an non existence NAD
```
I0516 22:17:04.157346       1 controller.go:353] "About to update node slices for network-attachment-definition" resourceName="default/macvlan-config-with-fast-ipam" network-attachment-definition="default/macvlan-config-with-fast-ipam"
```
But the log previously is happy about that NAD.
Do you think the namespace should be updated to the current one?

**Comment by NTmatter** [comment]
A bit late to the party, but the network range and slice size look a little out.

The /22 slice is larger than the /24 network, so these should be swapped. The /22 range is also 192.168.0.0-192.168.3.255/22.

This might work a bit better:
```
"range": "192.168.2.0/22",
"node_slice_size": "/24",
"network_name": "donkeykongjr",
```
